version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: library
    volumes:
      - db:/var/lib/postgresql/data
    restart: always

volumes:
  db:
